### PR TITLE
Fixing UI issues for audience

### PR DESCRIPTION
**Pull request by sanjeevbigstep**

### CODE REVIEW

**Comment by digitallysavvy** [comment]
@sanjeevbigstep you need to make sure there arent any conflicts... the UI tile fix was pushed by another user. please resolve this conflict

**Comment by sanjeevbigstep** [comment]
> @sanjeevbigstep you need to make sure there arent any conflicts... the UI tile fix was pushed by another user. please resolve this conflict

@digitallysavvy , sure, I will check and fix the same. Thanks.

**Comment by sanjeevbigstep** [comment]
> > @sanjeevbigstep you need to make sure there arent any conflicts... the UI tile fix was pushed by another user. please resolve this conflict
> 
> @digitallysavvy , sure, I will check and fix the same. Thanks.

@digitallysavvy conflicts have been resolved. Please have a look into it. Thanks.

**Comment by EkaanshArora** [comment]
@digitallysavvy lgtm, please take a look

**Pull request merged**
